spring:
  cloud:
    stream:
      function:
        definition: squaredNumberConsumer
      bindings:
        squaredNumberConsumer-in-0:
          destination: squaredNumbers
      kafks:
        binder:
          brokers:
            - localhost:9092